name: CI

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:

jobs:
  test-linux-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-full cmake pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip install conan

      - name: Detect Conan profile
        run: source .venv/bin/activate && conan profile detect --force

      - name: Install dependencies with Conan
        run: source .venv/bin/activate && conan install . --build=libuv/1.49.2 -o libuv/*:shared=True

      - name: Build with CMake
        run: |
          source .venv/bin/activate
          cmake --preset conan-release
          cmake --build ./build/Release

      - name: Run tests
        run: cd build/Release && ctest

  test-linux-Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-full cmake pip
          python3 -m venv .venv
          source .venv/bin/activate
          pip install conan

      - name: Detect Conan profile
        run: source .venv/bin/activate && conan profile detect --force

      - name: Install dependencies with Conan
        run: source .venv/bin/activate && conan install . --build=libuv/1.49.2 -s build_type=Debug -o libuv/*:shared=False

      - name: Build with CMake
        run: |
          source .venv/bin/activate
          cmake --preset conan-debug -DCMAKE_BUILD_TYPE=Debug
          cmake --build ./build/Debug

      - name: Run tests
        run: cd build/Debug && ctest
